version: "3"

services:
  server:
    container_name: 'sharp-cloud-uploader'
    image: ${DOCKER_IMAGE:-caomeiyouren/sharp-cloud-uploader}
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: "Asia/Shanghai"
      LOGFILES: "true"
    volumes:
      - ./logs:/app/logs
