packages:
  - "."

strictPeerDependencies: false

overrides:
  compare-func: ^2.0.0
  esbuild: ^0.25.4
  path-to-regexp: ^6.3.0
  undici: ^5.29.0
  glob: ^11.1.0
  js-yaml: ^4.1.1
  tmp: ^0.2.4

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
